### ISSUE TITLE
localization file path issue

### ISSUE THREAD

**Issue by poundbangbash** [tuxudo/thunderbolt#1]
On my 10.14.4 machine I the System Profiler Thunderbolt localization file is in `/System/Library/SystemProfiler/SPThunderboltReporter.spreporter/Contents/Resources/English.lproj` which counters the os version check logic.

Maybe best to check if the path exists and use it if it does?

**Comment by poundbangbash** [comment]
Proposed fix at https://github.com/tuxudo/thunderbolt/pull/2

**Comment by tuxudo** [comment]
Commit merged, thank you!
