### ISSUE TITLE
Error on M1 Macs

### ISSUE THREAD

**Issue by ofirgalcon** [tuxudo/thunderbolt#3]
I'm seeing this error on M1 MBA

`Server An error occurred while processing: Thunderbolt_model
Server Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xxxxxxxx' for key 'thunderbolt_serial_number_unique'`

It looks like this 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/16665880/105269887-b24ef480-5b8c-11eb-942a-daad15912c2c.png">

**Comment by tuxudo** [comment]
This has been resolved with version v2.1 of the module.
